permissions:
  contents: read
  actions: write
name: Android CI

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      TMDB_API_TOKEN: ${{ secrets.TMDB_API_TOKEN }}
      TEAMS_WEBHOOK_URL: ${{ secrets.TEAMS_WEBHOOK_URL}}
    
    steps:
    - name: Enable KVM group perms
      run: |
        echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
        sudo udevadm control --reload-rules
        sudo udevadm trigger --name-match=kvm
        ls /dev/kvm
    
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '17'

    - name: Set up Android SDK
      uses: android-actions/setup-android@v3

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4

    - name: Grant execute permission for gradlew
      run: chmod +x ./gradlew

    - name: Run Unit Tests
      run: ./gradlew testDebugUnitTest
    
    - name: Build APK
      run: ./gradlew assembleDebug

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: app-debug-apk
        path: app/build/outputs/apk/debug/app-debug.apk

    - name: Start Android Emulator and run instrumentation tests
      uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: 35
        arch: x86_64
        disable-animations: true
        disk-size: 6000M
        heap-size: 600M
        emulator-options: -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
        script: ./gradlew connectedAndroidTest
    
  notify:
    needs: build
    if: always()
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
  
      - name: Prepare Teams Notification Payload
        run: |
          cp .github/teams-workflow-payload.json payload.json
  
          if [ "${{ needs.build.result }}" = "success" ]; then
            STATUS_TEXT="✅ Success"
            STATUS_COLOR="Good"
          else
            STATUS_TEXT="❌ Failed"
            STATUS_COLOR="Attention"
          fi
          
          sed -i "s|WORKFLOW_NAME|${{ github.workflow }}|g" payload.json
          sed -i "s|ACTOR_NAME|${{ github.actor }}|g" payload.json
          sed -i "s|ACTOR_AVATAR_URL|https://github.com/${{ github.actor }}.png|g" payload.json
          sed -i "s|RUN_URL|${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|g" payload.json
          sed -i "s|STATUS_TEXT|$STATUS_TEXT|g" payload.json
          sed -i "s|STATUS_COLOR|$STATUS_COLOR|g" payload.json
  
      - name: Send Adaptive Card to Teams
        run: |
          curl -X POST "${{ secrets.TEAMS_WEBHOOK_URL }}" \
            -H "Content-Type: application/json" \
            --data-binary "@payload.json"
